name: ybb
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.0.1+2
  animator: ^2.0.2
  cached_network_image: ^2.0.0-rc.1
  cloud_firestore: ^0.14.4
  cupertino_icons: ^1.0.0
  firebase_auth: ^0.18.4
  firebase_core: ^0.5.3
  firebase_messaging: ^7.0.3
  firebase_storage: ^5.2.0
  flutter_svg: ^0.18.0
  geolocator: ^6.1.9
  geocoding: ^1.0.5
  google_sign_in: ^4.5.6
  html: ^0.14.0+4
  http: ^0.12.2
  image: ^2.1.19
  image_picker: ^0.6.7+14
  imagebutton: ^0.0.6
  intl: ^0.16.1
  path_provider: ^0.5.0+1
  simple_animations: ^2.4.0
  timeago: ^2.0.29
  uuid: ^2.2.2
  webview_flutter: ^1.0.7
  package_info_plus: ^0.6.3
  splashscreen: ^1.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
  assets:
    - assets/images/google_signin_button.png
    - assets/images/placeholder_ybb_news.jpg
    - assets/images/upload.svg
    - assets/images/search.svg
    - assets/images/activity_feed.svg
    - assets/images/no_content.svg
    - assets/images/ybb_logo.png
    - assets/images/1.png
    - assets/images/no_comment.svg
    - assets/images/no_notif.svg
    - assets/images/no_search.svg
    - assets/images/no_post.svg
    - assets/images/no_search_result.svg
    - assets/images/add_image.svg
    - assets/images/add_image_post.png
    - assets/images/loading_bg.svg
    - assets/images/info.svg
    - assets/images/info_data.svg
    - assets/images/welcome.svg
    - assets/images/ybb_black_full.png
    - assets/images/ybb_putih_cropped.png
    - assets/images/google_logo.png
    - assets/images/google_signin_button.png