name: ybb
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.1.2+23

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.0.1+2
  animator: ^2.0.2
  cached_network_image: ^2.0.0-rc.1
  cloud_firestore: ^0.14.4
  cupertino_icons: ^1.0.0
  extended_image: ^0.7.2
  file_picker: ^2.1.7
  firebase_auth: ^0.18.4
  firebase_core: ^0.5.0
  firebase_messaging: ^7.0.3
  firebase_storage: ^5.2.0
  flutter_email_sender: ^4.0.0
  flutter_svg: ^0.18.0
  google_sign_in: ^4.5.6
  html: ^0.14.0+4
  http: ^0.12.2
  image: ^2.1.19
  image_picker: ^0.6.7+14
  imagebutton: ^0.0.6
  intl: ^0.16.1
  meta: ^1.1.8
  package_info_plus: ^0.6.3
  path_provider: ^1.1.2
  rxdart: ^0.23.0
  shimmer: ^1.1.2
  simple_animations: ^2.4.0
  splashscreen: ^1.3.5
  timeago: ^2.0.29
  uuid: ^2.2.2
  webview_flutter: ^1.0.7
  curved_navigation_bar: ^0.3.7
  launch_review: ^1.0.1
  dropdown_formfield: ^0.1.3
  liquid_pull_to_refresh: ^2.0.0
  flutter_spinkit: ^4.1.2+1
  connectivity_wrapper: ^1.0.4
  font_awesome_flutter: ^8.11.0
  url_launcher: ^5.7.10
  flutter_local_notifications: ^3.0.2
  shared_preferences: ^0.5.12+4
  geocoding: ^1.0.5
  geolocator: ^6.1.1
  fluttertoast: ^7.1.8
  country_picker: ^1.0.4
  timeline_tile: 1.0.0
  photo_view: 0.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.0

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/images/ybb_logo.png'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Thin.otf
          weight: 100
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
  assets:
    - assets/images/google_signin_button.png
    - assets/images/placeholder_ybb_news.jpg
    - assets/images/upload.svg
    - assets/images/search.svg
    - assets/images/activity_feed.svg
    - assets/images/no_content.svg
    - assets/images/ybb_logo.png
    - assets/images/1.png
    - assets/images/img_not_available.jpeg
    - assets/images/no_comment.svg
    - assets/images/no_notif.svg
    - assets/images/no_search.svg
    - assets/images/no_post.svg
    - assets/images/no_search_result.svg
    - assets/images/add_image.svg
    - assets/images/add_image_post.png
    - assets/images/loading_bg.svg
    - assets/images/info.svg
    - assets/images/info_data.svg
    - assets/images/welcome.svg
    - assets/images/no_internet.svg
    - assets/images/ybb_black_full.png
    - assets/images/ybb_putih_cropped.png
    - assets/images/google_logo.png
    - assets/images/google_signin_button.png
    - assets/images/connected.svg
    - assets/images/connecte.svg
    - assets/images/contributing.svg
    - assets/images/portal.jpg
